### ISSUE TITLE
CSS compression breaks clamp()

### ISSUE THREAD

**Issue by jship** [jaspervdj/hakyll#1021]
Given this CSS:

```css
html {
  font-size: clamp(2.25rem, 2vw + 1.5rem, 3.25rem);
}
```

`compressCssCompiler` will strip the spaces around `+`, which makes the property value invalid.

```css
html{font-size:clamp(2.25rem,2vw+1.5rem,3.25rem)}
```

Perhaps [`compressCalcExpression`](https://github.com/jaspervdj/hakyll/blob/5b2e4739417189239ea69189bb02344175a0bd08/lib/Hakyll/Web/CompressCss.hs#L65-L68) could be applied over `clamp` values to get the same space-preserving behavior as `calc` values?
