### ISSUE TITLE
Nested fields in metadata

### ISSUE THREAD

**Issue by anatoliykmetyuk** [jaspervdj/hakyll#528]
It is often convenient to define your data in hierarchies, for example:

```yaml
social:
  twitter: Foo
  facebook: Bar
  github:
    name: Foo
    stars: 9999
    repos: 10

theme:
  link_color: #000000
  header_color: #111111
```

And access that from the templates: `$social.github.name$`. This is supported in Jekyll and is very convenient, but I can't see a way to do that in Hakyll. Is it possible to do that out of the box? Is it possible to easily write a plugin for that?
